services:
  mail2tg:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "0.0.1"   # версия приложения, передаётся в ldflags
    container_name: mail2tg
    environment:
      - TZ=Europe/Moscow       # таймзона контейнера
    ports:
      - "9090:9090"            # порт для метрик Prometheus
    volumes:
      - ./config:/app/config   # конфигурация и secrets
      - ./logs:/app/logs       # лог-файлы
    restart: unless-stopped